name: Deploy CDK project

on:
  push:
    branches: [ "master" ]

jobs:
  synth:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install

    - name: Synthesize CloudFormation Template
      run:  |
          npm install -g aws-cdk
          cdk synth
          echo "Synth successful"
      
